server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    product: birt #产品
    module: report #模块
    name: demo #子模块名称
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ############
    username: ######
    password: ####
    #初始化连接数量，最大最小连接数
    initialSize: 5
    maxActive: 10
    minIdle: 3
    #获取连接等待超时的时间
    maxWait: 600000
    #超过时间限制是否回收
    removeAbandoned: true
    #超过时间限制多长
    removeAbandonedTimeout: 180
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 600000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50


eureka:
  client:
    registry-fetch-interval-seconds: 3
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    status-page-url: http:localhost:${server.port}/swagger-ui.html
    metadata-map:
      user.name: admin
      user.password: 123456

host:
  stockservice: http://127.0.0.1:8080
